### PR TITLE
Project: Bare Metal Forms and Helpers

### PR DESCRIPTION
**Pull request by M-Alamgir**
Build some forms, both using nearly-pure HTML and then graduating to using the helper methods that Rails provides.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Alamgir Alamgir** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Fix rubocop offenses
- [x] You are not following the correct git flow, your should make your pull request from the feature branch (or some other descriptive name) to your develop/development branch.

### OPTIONAL

- [x] It would be nice to validate the email format
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by M-Alamgir** [comment]
There are no rubocop offenses and I have added the active record validation to validate the email format,
I have renamed the production branch to main branch but sorry I cannot rename the development branch now because if I do it will automatically close the pull request.
Thanks.

**Comment by M-Alamgir** [comment]
There are no rubocop offenses and I have added the active record validation to validate the email format,
I have renamed the production branch to main branch but sorry I cannot rename the development branch now because if I do it will automatically close the pull request. But in future projects I'll keep this in mind.
Thanks.

**Review by mke2111 — APPROVED** [review]
# STATUS: APPROVED  🟡

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

> Always keep in mind the appropriate use of Git/Github flow from now on. I'll approve this based on the fact that you will. 😄 

### You may now merge to the develop/main branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Pull request merged**
